[package]
name = "ruru"
version = "0.5.2"
authors = ["Dmitry Gritsay <unseductable@gmail.com>"]

description = "Native Ruby extensions in Rust"
documentation = "http://d-unseductable.github.io/ruru/ruru/index.html"
homepage = "https://github.com/d-unseductable/ruru"
repository = "https://github.com/d-unseductable/ruru"
readme = "README.md"
keywords = ["ruby", "ruru"]
license = "MIT"

build = "build/build.rs"
links = "ruby"

[dependencies]
libc = "0.2.10"
